app = "cinephoria-frontend"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "dist/cinephoria-frontend/browser"
  url_prefix = "/"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
